### ISSUE TITLE
Database Error - 

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#101]
After I downloaded the new 4.0 today and have brought to my server up and running, I realized that a Medic is a license buy them in the database in the equestrian cop_gear saved.

**Comment by hitem** [comment]
https://github.com/Itsyuka/Altis-Life/pull/80 make sure you switch the numbers %4 and %5 incase your database it setup like that.

**Comment by Provokan** [comment]
that doesn work :)

on my fn_queryRequest.sqf its this 

	case west: {_returnCount = 10; format["playerWestInfo:%1",_uid];};
	case civilian: {_returnCount = 9; format["playerCivInfo:%1",_uid];};
	case independent: {_returnCount = 9; format["playerIndependentInfo:%1",_uid];};

when i change your fixx i dont can join as medic

**Comment by Provokan** [comment]
Fixxed thanks :)
