### ISSUE TITLE
Vehicle Rental its buggy,

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#106]
when i delete a classname from the rental list, i cant buy this permanent :) any fixx here?

**Comment by breaup** [comment]
Is it added to the shops you want to buy it from? I have no issues on my end it seems to be working fine

**Comment by Provokan** [comment]
My config_vehicle -> 

	class reb_car {
		side = "civ";
		vehicles[] = {
			{ "B_Quadbike_01_F", 5000, "rebel" },
			{ "B_G_Offroad_01_F", 15000, "rebel" },
			{ "B_Heli_Light_01_F", 325000, "rebel" },
			{ "O_Heli_Light_02_unarmed_F", 625000, "rebel" },
			{ "I_Heli_Transport_02_F", 2000000, "rebel" },
			{ "B_G_Offroad_01_armed_F", 750000, "rebel" },
			{ "O_MRAP_02_F", 8000000, "rebel" },
			{ "O_MRAP_02_hmg_F", 16000000, "rebel" },
			{ "I_MRAP_03_F", 14000000, "rebel" },
			{ "I_MRAP_03_hmg_F", 18000000, "rebel" }
			
		};
	};

and the line from my rental only 

	vehicleShop_rentalOnly[] = { "B_G_Offroad_01_armed_F" };

and i can only rental the Hunter HMG

**Comment by hitem** [comment]
You have that line in Config_Master.hpp AND fn_vehicleShopBuy.sqf 
Make sure you change both of them accordingly
