### ISSUE TITLE
Huge mistake in the EXTDB

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#108]
I have a very large gap found in the found EXTDB when I use in my name the following special characters: [],: /, / {}, I can every server crash that uses the Altis Life 4.0

**Comment by BAROD** [comment]
ehm BEC 

DisallowPlayerNameChars = [](){}<>/\^|Â§!#%&@Â£Â¤Â¨

dafuck

**Comment by Provokan** [comment]
yes, but not all Serves use BEC :)

**Comment by BAROD** [comment]
+

https://github.com/Itsyuka/Altis-Life/blob/master/%40extDB/extdb/db_custom/altis-life-rpg-4.ini#L273

use the string option for the name

**Comment by Provokan** [comment]
Nice works :) i love u :b

**Comment by Provokan** [comment]
can u make a example with the string for the name?

**Comment by BAROD** [comment]
http://pastebin.com/srpikDUK

**Comment by Provokan** [comment]
ok thanks ^^ but i think the string on the 1 and not on the cash or?
