### ISSUE TITLE
WantedUpdateName Crash

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#110]
Once a civilian played at the server named XYZ and is on the wanted list, he logs out and then changed its name to ZYX, it crashes with the following error message the server

[16:05:37 +02: 00] [thread 1180705119] EXTDB: DB_CUSTOM_V5: Incorrect Number of inputs: Input string wanted updatename: Raktik: PLAYERID

**Comment by ColinM9991** [comment]
Just to mention for everybody,. I'm finished college in 2 days and once that's done I will be working on this wanted system to get it working with 4.0 completely; but that doesn't mean I'm going to be working on or fixing 4.0

**Comment by BAROD** [comment]
oh gg Colin,

**Comment by ColinM9991** [comment]
Fixed

https://github.com/Itsyuka/Altis-Life/commit/3efda470bc4be02c0ac52148e7de52c4456d00a7
