### ISSUE TITLE
After Update -> Vehicle weight  & OpenInventory

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#116]
_weight = M_CONFIG(getNumber,CONFIG_VEHICLES,(typeOf _vehi>
 9:27:07   Error position: <(getNumber,CONFIG_VEHICLES,(typeOf _vehi>
 9:27:07   Error Fehlendes ;
 9:27:07 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_vehicleWeight.sqf, line 14

 9:27:07 Error in expression <ght = 0;
{_mWeight = _mWeight + M_CONFIG(getNumber,CONFIG_VEHICLES,(typeOf _x),">
 9:27:07   Error position: <(getNumber,CONFIG_VEHICLES,(typeOf _x),">
 9:27:07   Error Fehlendes ;
 9:27:07 File mpmissions\__CUR_MP.Altis\core\vehicle\fn_openInventory.sqf, line 29

**Comment by BAROD** [comment]
no it work (your copy paste fail Error Fehlendes ;)

**Comment by Provokan** [comment]
ok ^^ :dancer:

**Comment by BAROD** [comment]
#include
