### ISSUE TITLE
Colim - a little list of Errors :)

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#119]
2015/05/07, 14:35:50   Error Undefined variable in expression: _houses
2015/05/07, 14:35:50 File life_server\Functions\Housing\fn_houseCleanup.sqf, line 11

2015/05/07, 14:35:50   Error Undefined variable in expression: _queryresult
2015/05/07, 14:35:50 File life_server\Functions\MySQL\fn_asyncCall.sqf, line 61

2015/05/07, 14:24:59 Performance warning: SimpleSerialization::Write 'TON_fnc_player_query' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

2015/05/07, 14:24:59 Performance warning: SimpleSerialization::Write 'TON_fnc_index' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

2015/05/07, 14:24:59 Performance warning: SimpleSerialization::Write 'TON_fnc_isnumber' is using type of ',CODE' which is not optimized by simple serialization, falling back to generic serialization, use generic type or ask for optimizations for these types

2015/05/07, 14:24:59 Performance warning: SimpleSerialization::Write 'TON_fnc_clientGangKick' is using type of ',CODE' which is n

**Comment by m3talstorm** [comment]
The last 4 are not errors, it clearly says 'warning'.

**Comment by hitem** [comment]
https://github.com/Itsyuka/Altis-Life/pull/80/files
add the following line (altis-life-4.ini , you know, the custom DB) to 
[housingCleanup]

+OUTPUT= 1-String, 2-String, 3-AltisLifeRPG_Array, 4-AltisLifeRPG_Array

/hitem

Dominic skrev den 2015-05-07 15:35:

**Comment by Provokan** [comment]
nice works :b

**Comment by Provokan** [comment]
hitem, after u update -.> i become this error?

18:49:51 Error in expression <life_fnc_MP;
if(_valid isEqualTo false) then

if(life_atmbank < (_houseCfg selec>
18:49:51   Error position: <then

if(life_atmbank < (_houseCfg selec>
18:49:51   Error then: Typ if, erwartet Array,code
18:49:51 File mpmissions\__CUR_MP.Altis\core\housing\fn_buyHouse.sqf, line 31
