### ISSUE TITLE
EPE manager release (0|0|0)

### ISSUE THREAD

**Issue by grimzy101** [Itsyuka/Altis-Life#120]
Been looking all over the internet for the last 3-4 hours trying to look for something that could possibly fix this error, I believe that this is the error that's stopping my server.

So basically, I start my server up and everything's fine, but by the looks of it, all of a sudden it will just stop, or sometimes not start at all. I started off at the point where the server showed up in my filter and what not, I'd go to connect and it would just stay on the Altis loading screen, it wouldn't advance me any further, it wouldn't take me to the slot selections ect.

Now it's not showing up in the server filter at all.

http://pastebin.com/rk0hEcDd

Any help would be much appreciated...

**Comment by Floxxe** [comment]
Have a look @ your extDB-Log

**Comment by ColinM9991** [comment]
Not an issue
