### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by marhotiewer** [Itsyuka/Altis-Life#124]
Yesterday I installed a dedicated server and it was working fine with wasteland but then I decided that I wanted a altis server so i installed it but when I play on the  server i cant access my menu at all I cant use Y, left windows, U and I dont even see any options if I scroll with my mouse so basicly I can walk around but thats it can someone please help me 

I appreciate your help

p.s sorry for the bad english.

**Comment by ColinM9991** [comment]
Post on the Altis Life forums with server & client RPT files.
