### ISSUE TITLE
Cant open doors in house

### ISSUE THREAD

**Issue by zanris** [Itsyuka/Altis-Life#13]
Hi! I still have the problem with opening doors when buying a house, i click open but it only says LOCK all the time, i tried to take the code from Itsyukas altis-life, and added the house code for U-key in Keyhandler, but when i added it, all actionbuttons like , windows, y , SHIFT + H etc stopped working, anyone have any idea? would love to get it working so people can open their doors on my server.

Thanks!

**Comment by ColinM9991** [comment]
For the functions/buttons that stopped working, that's down to a coding issue.

Post this on the forums and provide server & client side RPT's ONLY ONCE the issue has been REPRODUCED.
