### ISSUE TITLE
Truck License issue

### ISSUE THREAD

**Issue by FatPiggy** [Itsyuka/Altis-Life#134]
In Config_Vehicles.hpp all the trucks need to look for the license called "trucking" not "truck"

Lines 48-60:

	class civ_truck {
		side = "civ";
		vehicles[] = {
			{ "C_Van_01_box_F", 60000, "truck" },
			{ "I_Truck_02_transport_F", 75000, "truck" },
			{ "I_Truck_02_covered_F", 100000, "truck" },
			{ "B_Truck_01_transport_F", 275000, "truck" },
			{ "O_Truck_03_transport_F", 200000, "truck" },
			{ "O_Truck_03_covered_F", 250000, "truck" },
			{ "B_Truck_01_box_F", 350000, "truck" },
			{ "O_Truck_03_device_F", 450000, "truck" }
		};
	};

to

	class civ_truck {
		side = "civ";
		vehicles[] = {
			{ "C_Van_01_box_F", 60000, "trucking" },
			{ "I_Truck_02_transport_F", 75000, "trucking" },
			{ "I_Truck_02_covered_F", 100000, "trucking" },
			{ "B_Truck_01_transport_F", 275000, "trucking" },
			{ "O_Truck_03_transport_F", 200000, "trucking" },
			{ "O_Truck_03_covered_F", 250000, "trucking" },
			{ "B_Truck_01_box_F", 350000, "trucking" },
			{ "O_Truck_03_device_F", 450000, "trucking" }
		};
	};

**Comment by Provokan** [comment]
or change on your Config_master truck to trunking, its easy

**Comment by FatPiggy** [comment]
Either one, just saying there is a discrepancy in the mission file.

**Comment by Provokan** [comment]
https://github.com/Itsyuka/Altis-Life/commit/1c38cd0eeda7a643913da8ff1142e11b85e8aab3 -> see this fix guy .

**Comment by FatPiggy** [comment]
Check these files:

https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/Altis_Life.Altis/Config_Vehicles.hpp
https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/Altis_Life.Altis/Config_Master.hpp

In the most recent build, there are discrepancies. It hasn't been "fixed"

**Comment by midgetgrimm** [comment]
Updated, thanks piggy
