### ISSUE TITLE
Vehicle Search

### ISSUE THREAD

**Issue by Demuth92** [Itsyuka/Altis-Life#137]
For some reason my Search vehicle doesn't work.. On a vehicle full of cocaine..

**Comment by Demuth92** [comment]
May explain this a bit better.. I can search a vehicle, it says in the chat that nothing illegal was found in the vehicle, with a vehicle full of cocain.

**Comment by Geniks** [comment]
It is unprocessed cocaine ?
Or have you got a custom market system ?

**Comment by midgetgrimm** [comment]
Nope, just fucked up because no one gives a shit. Too bad. Bascially it ends at 4.0 as it so broken, anything you do past that, you might as well add your name to the developer list

**Comment by Geniks** [comment]
no that's just because you misconfigured your server.
it works only if you have configured nice prices for drugs, because it's coded like that.

it works on my server so...

**Comment by midgetgrimm** [comment]
What the fuck is a nice price? Why don't you post a line of your nice prices so maybe we can see?

**Comment by midgetgrimm** [comment]
//Drugs
	VITEMMACRO(heroin_unprocessed, "STR_Item_HeroinU", "heroinUnprocessed", 6, 960, 660, true, -1, "")
	VITEMMACRO(heroin_processed, "STR_Item_HeroinP", "heroinProcessed", 4, 7960, 7560, true, -1, "")
	VITEMMACRO(cannabis, "STR_Item_Cannabis", "cannabis", 4, 800, 350, true, -1, "")
	VITEMMACRO(marijuana, "STR_Item_Marijuana", "marijuana", 3, 7800, 7350, true, -1, "icons\ico_marijuana.paa")
	VITEMMACRO(cocaine_unprocessed, "STR_Item_CocaineU", "cocaineUnprocessed", 6, 1300, 1000, true, -1, "")
	VITEMMACRO(cocaine_processed, "STR_Item_CocaineP", "cocaineProcessed", 4, 8300, 8000, true, -1, "")



and what is wrong here then?

**Comment by Geniks** [comment]
you didn't answer.
does it work with processed drugs or it doesnt work at all ?
and try : hint format ["%1", _value]; line 28 on fn_vehInvSearch.sqf

**Comment by midgetgrimm** [comment]
Well, either share to help or move on man, I've done all that and it still returns shit.I've messed around with it, and I will again, but I just moved on to other items as it wasn't pressing, then I saw this post here. So if you want to help people, than share some of your code, like your config, and vehSearchInv file. Thanks

**Comment by Geniks** [comment]
Are you dumb ??
What am i doing if it's not helping you ?
I can't share you my file because it is modified for a dynamic market script.

So i told : try to add hint format ["%1", _value]; line 28 on fn_vehInvSearch.sqf

**Comment by midgetgrimm** [comment]
lol. Listen fucktard, you giving a hint value is less than helpful, but because your idiotic response annoyed me, I fixed the problem. But fuck you anyway :) have a nice day

**Comment by Geniks** [comment]
oh my god ! you're amazing ! you finded how it works, and you found it !
so nice !

**Comment by midgetgrimm** [comment]
Have you met Jesus?

**Comment by TheValthos** [comment]
Of-course he knows Jesus. French are very well known for getting on there knees.

**Comment by m3talstorm** [comment]
their*

**Comment by TheValthos** [comment]
Screw you Metal :) x

**Comment by midgetgrimm** [comment]
Check latest commits for some fixes guys
