### ISSUE TITLE
Wanted List not populating but adding to db

### ISSUE THREAD

**Issue by breaup** [Itsyuka/Altis-Life#143]
I reloader all the wanted system from this github but I get this error in the client RPT Files when opening the wanted list or adding someone on it

 6:52:19 Error in expression <pile format["%1", _criminal];

[[player,_criminal],"life_fnc_wantedCrimes",false>
 6:52:19   Error position: <_criminal],"life_fnc_wantedCrimes",false>
 6:52:19   Error Undefined variable in expression: _criminal
 6:52:19 File mpmissions\__CUR_MP.Altis\core\cop\fn_wantedGrab.sqf, line 15
 6:52:19 Error in expression <03,format[localize "STR_Wanted_Bounty",[_bounty] call life_fnc_numberText]]; >
 6:52:19   Error position: <_bounty] call life_fnc_numberText]]; >
 6:52:19   Error Undefined variable in expression: _bounty
 6:52:19 File mpmissions\__CUR_MP.Altis\core\pmenu\fn_wantedInfo.sqf, line 33

**Comment by breaup** [comment]
So I checked tonight the extdb error I get is
 mysql_stmt_execute error	[mysql_stmt_error]: Duplicate entry '76561198056853578' for key 'PRIMARY'	[mysql_stmt_errno]: 1062	[mysql_stmt_sqlstate]: 23000	[statemnt]: INSERT INTO wanted (wantedID, wantedName, wantedCrimes, wantedBounty, active) VALUES(?,?,?,?,?);

Trying to insert a duplicate entry, so what I did I changed the sql to delete the entry when you pardon someone from the wantedlist but for the Updating part its not firering. 

When I look at the wanted add below it looks all right to me, if not exist insert if there update but it seems when trying to manually add someone to the wanted list it's still trying to insert even if the ID Exist. 

//Search the wanted list to make sure they are not on it.

_result = format["wantedGetCrimes:%1",_uid];
waitUntil{!DB_Async_Active};
_queryResult = [_result,2] call DB_fnc_asyncCall;

_val = [(_type select 1)] call DB_fnc_numberSafe;

if(count _queryResult != 0) then
{
	_pastCrimes = _queryResult select 1;
	_pastCrimes pushBack (_type select 0);
	_query = format["wantedUpdateCrimes:%1:%2:%3",_pastCrimes,_val,_uid];
} else {
	_crimes = [(_type select 0)];
	_query = format["wantedInsertCrimes:%1:%2:%3:%4:1",_uid,_name,_crimes,_val];
};

**Comment by ColinM9991** [comment]
diag_log the _queryResult from the wantedGetCrimes result and paste it back here.

**Comment by ThatFellaNick** [comment]
Does anyone have a fix? Need it bad

**Comment by breaup** [comment]
Mine works on and off ... I don't know what to tell you. I reloaded my .ini for the extdb maybe it helpded

**Comment by ThatFellaNick** [comment]
I had to roll back to 3.1.4.8

**Comment by ivaylosp** [comment]
The problem for the wanted list not populating is connected to a extDB problem. You will notice that if there is only 1 wanted player online everything works as expected but when you have 2 players the list is empty. There is a script on altisliferpg.com that works around this issue by pulling all the wanted list players and not only the one online and then they loop trough the list and populate the one that are online only. It is not the right approach but it fixes the problem.

**Comment by breaup** [comment]
Have the link for the script ? would be really helpful, I was going to modify the query to show all active wanted level instead even player is online or not.

**Comment by ivaylosp** [comment]
This is the article that explains how to script a workaround this issue:
http://www.altisliferpg.com/topic/10431-extdb-wanted-list-issue/?hl=wanted
