### ISSUE TITLE
extDB was not loaded into the engine

### ISSUE THREAD

**Issue by tomgie** [Itsyuka/Altis-Life#144]
Ok I am running the server on Debian 7 and have tried EVERYTHING to fix this problem. I have gone on countless forums. On this github website and tried things myself! It does not work!
I keep getting the same error:

"extDB: Version: "
"The server-side extension extDB was not loaded into the engine report this to the server admin."

I am using the latest version of extDB

**Comment by Provokan** [comment]
U change on the extdb the Database2 to AltisLife?

**Comment by ColinM9991** [comment]
Not an issue with Altis LIfe.
