### ISSUE TITLE
PLAYER GET KICKED ON LOGIN

### ISSUE THREAD

**Issue by felipetmartini** [Itsyuka/Altis-Life#149]
A cracked clients can join on this server? For my client when try join on server i got instantly kicked,

Have a way to run this server for no official clients?
To not check steam or other things?

For me on server console show thats my client have a modified data folder,

Can someone help me?

**Comment by stuartbannerman** [comment]
Ye, buy the game...

**Comment by Provokan** [comment]
please go with this problem on the official altislifeforum www.altisliferpg.com
