### ISSUE TITLE
Exception code: 0xc0000094

### ISSUE THREAD

**Issue by y7deadman** [Itsyuka/Altis-Life#155]
Faulting application name: arma3server.exe, version: 1.48.131.645, time stamp: 0x55b63842
Faulting module name: arma3server.exe, version: 1.48.131.645, time stamp: 0x55b63842
Exception code: 0xc0000094
Fault offset: 0x00d33484
Faulting process id: 0xc0c
Faulting application start time: 0x01d0dadd4b8d7980
Faulting application path: C:\Users\Administrator\Desktop\AltisLife\Steam\steamapps\common\Arma 3 Server\arma3server.exe
Faulting module path: C:\Users\Administrator\Desktop\AltisLife\Steam\steamapps\common\Arma 3 Server\arma3server.exe
Report Id: 6a91100c-46d1-11e5-8c74-002590679dd9

**Comment by chris579** [comment]
Related to arma 3, not altis life:

feedback.arma3.com
