### ISSUE TITLE
Can't carry items from mods

### ISSUE THREAD

**Issue by Slim57050** [Itsyuka/Altis-Life#159]
Hello , i installed ACE3 on my server and added items to shop (4.0 , in config_shops.hpp)

Item are here and i show prices , i can buy it but they not go in my inventory.

I have opened a issues on ACE3 github and they say me " Mission fault" so how can i "whitelist" item from mods? thx.

**Comment by Povers** [comment]
Hi,

For buy ACE3 items with Altis Life you,you must change a few lines in fn_handleItem.sql (core/functions).

See it around line 135 :

if(_item in (assignedItems  player)) then 
								{
									player addItem _item;
								} 
									else 
								{
										player addItem _item; 
										if(!(["ACE_",_item] call BIS_fnc_inString)) then {
										player assignItem _item;
									};
								};

**Comment by chris579** [comment]
However, Altis Life doesn't supports mods. You have to figure it out for yourself.

**Comment by Slim57050** [comment]
Thx Povers it work!
