### ISSUE TITLE
Tazer invisible

### ISSUE THREAD

**Issue by MaximumAltis** [Itsyuka/Altis-Life#16]
//_obj = "Land_ClutterCutter_small_F" createVehicleLocal ASLTOATL(visiblePositionASL player); //Again why in the fuck was this being created globally? I could of                         sworn I made it local back in ARMA 3 Beta...
//_obj setPosATL ASLTOATL(visiblePositionASL player);

if those two lines are not commented out it will cause people to become invisible when tazed

**Comment by Itsyuka** [comment]
I already know
