### ISSUE TITLE
Fix script errors

### ISSUE THREAD

**Issue by Itsyuka** [Itsyuka/Altis-Life#2]
-DP
-Few others

**Comment by Itsyuka** [comment]
-DP Fixed
-Hunting zone needs to be fixed.

**Comment by Itsyuka** [comment]
-Search Client fixed.

**Comment by Itsyuka** [comment]
-Hunting zone works, just hard to find them (GG Tonic)
-Garage menu not being opened via Action key

**Comment by ColinM9991** [comment]
-Garage menu not being opened via Action key (FIXED)
