### ISSUE TITLE
Gang Leave Bug

### ISSUE THREAD

**Issue by GamerDF** [Itsyuka/Altis-Life#21]
GUID wont be delete by leaving an gang, and People cant creat an new one, messege is coming up "You are currently already active in a gang, please leave the gang first."

**Comment by MaximumAltis** [comment]
^^

**Comment by ColinM9991** [comment]
I'll have a look at this today after college

On 9 February 2015 at 03:19, MaximumAltis <notifications@github.com> wrote:

> ^^
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Itsyuka/Altis-Life/issues/21#issuecomment-73452266>.
>



-- 
Sincerely,

Colin

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/29

**Comment by MaximumAltis** [comment]
Any update on this?

**Comment by Geniks** [comment]
On leave, on or kick ?
Or both ?
