### ISSUE TITLE
Backpack Bug

### ISSUE THREAD

**Issue by calswpark** [Itsyuka/Altis-Life#25]
lets say you buy a backpack, ur inventory space is lets say around 80.
 if you buy another one while u have a backpack, the inventory spaces appends on
 so you would have lets say 200.

**Comment by BAROD** [comment]
you changed something?

**Comment by calswpark** [comment]
this is on vanilla 4.0

**Comment by BAROD** [comment]
uh jeah

**Comment by calswpark** [comment]
any ideas

**Comment by BAROD** [comment]
push it later

**Comment by BAROD** [comment]
fix https://github.com/Itsyuka/Altis-Life/pull/28
