### ISSUE TITLE
Another Backpack bug:

### ISSUE THREAD

**Issue by calswpark** [Itsyuka/Altis-Life#31]
Another Backpack bug:

Example Scenario:

Player goes to the clothing npc,
clicks on the, for example, the most highest-inventory backpack, doesnt buy
then clicks on, for example, a lesser-inventory backpack and clicks buy.

ultimately, player is left with the most highest inventory backpack but only pays the price of the "lesser-inventory" backpack.

Hopes this makes sense.

**Comment by ColinM9991** [comment]
I have spare time today, I'll have a look this and other various bugs when I'm finished work.

**Comment by mjmfighter** [comment]
Not the only problem with backpacks.  You can purchase as many things as you can carry, for the price of one.

Example:
Go to the vests and click to buy one.  Change your mind and spam click on another vest (just double click it a few times).  Click buy.  Got lots of vests for price of one.

**Comment by Itsyuka** [comment]
Yea I don't get that issue, only with that hats and that I just patched.
