### ISSUE TITLE
Robbing setup action

### ISSUE THREAD

**Issue by MaximumAltis** [Itsyuka/Altis-Life#41]
When knocking someone down, the setup action for robbing never appears.

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/42

Close

**Comment by MaximumAltis** [comment]
change it, still no function to rob them

**Comment by BAROD** [comment]
it work

**Comment by BAROD** [comment]
now? 
https://github.com/Itsyuka/Altis-Life/pull/43

**Comment by MaximumAltis** [comment]
yeah it worked :) thanks
