### ISSUE TITLE
FuelCans

### ISSUE THREAD

**Issue by ghost** [Itsyuka/Altis-Life#44]
When players use the fuel cans to fuel up their vehicles, nothing seem to happen.

Not 100% sure if this is vanilla 4.0.0.

Apologize in advance for putting useless shit up here if thats not the case.

**Comment by calswpark** [comment]
the entity name in fuelcans in useitem.sqf is wrong.

**Comment by Provokan** [comment]
than push the right name plese :)

**Comment by hitem** [comment]
Its wrong on more places then only useitem. replace fuelF with fuelFull

**Comment by Provokan** [comment]
case (EQUAL(_item,"fuelFull")): {
		if(vehicle player != player) exitWith {hint localize "STR_ISTR_RefuelInVehicle"};
		[] spawn life_fnc_jerryRefuel;
	}; -> thats my fixx and this doesn work.

**Comment by hitem** [comment]
As mention earlier, its more then 1 place you need to change this, search for "fuelf" and fill it in with "fuelfull"

**Comment by Provokan** [comment]
i found only the post with case (equal ....

hier my useItem.sqf
http://pastebin.com/4APUiDvf

**Comment by Provokan** [comment]
ok must to be change on fn_jerryrefuel on line 15

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/112
