### ISSUE TITLE
Paycheck Error client.fsm

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#48]
Good evening, I have the following for the use of 4.0 problem
in the client.fsm there are problems with the paycheck period.
It is not the money, but the money is in the Database to 0.

Currently, I get the following error message every 5 min

21:49:56 Error in expression <ayer, (profile name), player side, life_cash, life_atmbank];
_array = [];
_flag = swit>
21:49:56 Error position: <life_atmbank];
_array = [];
_flag = swit>
21:49:56 Error Undefined variable in expression: life_atmbank

Is there a possibility to fixxen this error?

Sry for my bad english :-/ 

German 
_________________________________________________________________________
Guten Abend, ich habe folgendes problem mit der 4.0, in der Client.Fsm gibt es ein fehler mit der PayCheck periode. Es sieht derzeit so aus dass wenn man ein PayCheck erhält man folgenden Fehler erhält 21:49:56 Error in expression <ayer, (profile name), player side, life_cash, life_atmbank];
_array = [];
_flag = swit>
21:49:56 Error position: <life_atmbank];
_array = [];
_flag = swit>
21:49:56 Error Undefined variable in expression: life_atmbank

Ist es möglich dies zu beheben?

**Comment by MaximumAltis** [comment]
life_atmbank should be BANK if macro.h is being used

**Comment by BAROD** [comment]
life_atmbank == life_atmcash or BANK

**Comment by Provokan** [comment]
thanks for your helping :) its work
