### ISSUE TITLE
Drug dealers not setup

### ISSUE THREAD

**Issue by MaximumAltis** [Itsyuka/Altis-Life#5]
The drug dealers are currently not setup on the Altis Life 4.0 - 

When going to the drug dealer is says the config file is not setup

http://i.imgur.com/NtMIdWd.jpg

**Comment by ColinM9991** [comment]
Is this running stock & latest version from Yuka's build?

You can throw a diag_log in to core\pmenu\fn_virt_menu.sqf to log the _shop and see what it is being returned, if it's "drugdealer" then you're using an invalid-something.

**Comment by MaximumAltis** [comment]
Stock and latest verison from Yuka's build - Yes

kinda lost about adding the dia_log in the virt_menu,sqf , also with that being said there is not even a fn_virt_menu.sqf in the pmenu folder, it is stored in shops folder?

**Comment by ColinM9991** [comment]
Sorry, core\shops is the right path.

diag_log str _shop; //After the _shop declaration

**Comment by MaximumAltis** [comment]
Hmm strange, everything is correctly setup like it should, i went to the fn_virt_menu.sqf file and it all checks out with the on itsyuka, i then went to fn_virt_shops.sqf and there is a heroin case there, with cocaine and heroin and mary jane like it should, i decided to open the NPC on mission editor and it calling the right files such as the ones i posted above, i will try to look at it again and will post if i find anything else.

**Comment by MaximumAltis** [comment]
downloaded the very very latest and now it works, sorry for the trouble.
