### ISSUE TITLE
Logitech g27 (wheel) - disconnecting after pressing Esc?

### ISSUE THREAD

**Issue by WestOz-Col** [Itsyuka/Altis-Life#58]
Hello, 
When in Arma 3 the Logitech g27 is recognized in controls as a controller, configurable, fully functions in game, no issues.

Likewise immediately after logging into an Altis Life server the g27 is usable, fully functions.

However if I press Esc on the keyboard to make changes etc the g27 is immediately lost, no longer shows in controls as a controller.
Go back in play (continue) the previous working controls no longer function, requiring disconnection from server back to Arma 3 then reenter the server process.

I have setup a profile in the Logitech software, reset all A3 to presets, all macro functions work fine however I'm unable to generate turning functions with the steering wheel.

Any help appreciated, trust its a simple solution.

Regards

Col

**Comment by Itsyuka** [comment]
This isn't Bohemia Support, go to their forums and put a thread up.

**Comment by WestOz-Col** [comment]
Sorry, no issues whilst in Arma 3, only happens when in Altis-Life?
