### ISSUE TITLE
Gang bug even with the update #3 3/5/15

### ISSUE THREAD

**Issue by ghost** [Itsyuka/Altis-Life#61]

**Comment by BAROD** [comment]
because it has nothing to do with gang stuff:
-Updated housing, should now check to see if the house is already owned
by someone, even if they are not online
-Updated minor tweaks to the ini

**Comment by calswpark** [comment]
I mean all the update up to now. Someone told me yuka has got the gangs fixed. Just letting you guys know, thats all.

**Comment by BAROD** [comment]
nope

**Comment by Itsyuka** [comment]
Oh so close, I thought I could get away with it.

**Comment by BAROD** [comment]
not in this life...

**Comment by adigame** [comment]
Do you repairs this gang bug?  When can we expect released the functioning code?
