### ISSUE TITLE
BEFilter issue

### ISSUE THREAD

**Issue by DutchyD** [Itsyuka/Altis-Life#62]
I've installed everything correctly, but I keep getting kicked for 

#0 "this allowDamage false; this enableSimulation false; this addAction[format["%1 ($%2)",localize (getText(missionConfigFile >> "Li" 

by the scripts filter

**Comment by salutesh** [comment]
Same issue after fresh install :(

**Comment by salutesh** [comment]
Fix it with this in BE script.txt Line 1:
!"this addAction[format[/"%1 ($%2)/",localize (getText(missionConfigFile >> /"Li/""

**Comment by ColinM9991** [comment]
https://guides.github.com/features/mastering-markdown/
