### ISSUE TITLE
extDB2?

### ISSUE THREAD

**Issue by nanougames** [Itsyuka/Altis-Life#63]
Hi bro,

Can u put extDB2 on ur Altis Life for multiple thread..?

**Comment by Itsyuka** [comment]
It's possible

**Comment by nanougames** [comment]
Ok look my server bro : https://github.com/nanougames/Projet-BronX/commit/7dc40f66fb1ff38b2c7aceafa234be5e73d6e545

**Comment by harmdhast** [comment]
You could also remove those unseccured functions that execute sql code. If you want i can give you the modified files for extdb2 to work with AL

**Comment by FisherSam** [comment]
harmdhast hi! You could not publish files that are running extDB2?

**Comment by Floxxe** [comment]
@harmdhast That would be nice...

**Comment by TheValthos** [comment]
yea this world be really nice :)

**Comment by Itsyuka** [comment]
Working on the new version, https://github.com/Itsyuka/Altis-Life/tree/REV-DEV
