### ISSUE TITLE
db_custom/altis-life-rpg-4.ini#L316

### ISSUE THREAD

**Issue by Tomms123** [Itsyuka/Altis-Life#64]
[playerWestUpdate]
;;

SQL1_1 = UPDATE players
;;				1          2 	    3          4           5                   6
SQL1_2 = 		SET name=?, cash=?, bankacc=?, cop_gear=?, cop_license=? WHERE playerid=?

SQL1_INPUTS = 1, 2, 3, 4-AltisLifeRPG_Array, 5-AltisLifeRPG_Array, 6

Number of Inputs = 6

Silly willy it shall be cop_licenses=?

**Comment by Itsyuka** [comment]
Oh you :trollface:
