### ISSUE TITLE
Issue with .ini

### ISSUE THREAD

**Issue by dbenson24** [Itsyuka/Altis-Life#66]
vehicleUpdateAlive should look like so, as it is currently it causes a server crash when someone sells a vehicle
;;______________________________________________________________
[vehicleUpdateAlive]
;;

SQL1_1 = UPDATE vehicles SET alive=? WHERE pid=? AND id=?;

SQL1_INPUTS = 1, 2, 3
Number of Inputs = 3

**Comment by Tomms123** [comment]
Silly willy Itsyuka, he blaimed his staff so

**Comment by Itsyuka** [comment]
I blamed my staff on advertising, noob

**Comment by Tomms123** [comment]
Well okey then supreme commander.

**Comment by breaup** [comment]
Thanks bud your fix worked :)
