### ISSUE TITLE
TON_fnc_LogIt undefined variable?

### ISSUE THREAD

**Issue by DutchyD** [Itsyuka/Altis-Life#67]
After I've fixed the BEFilter issue, I've ran into another problem.

Everytime I start the server, I get stuck on setting up client, please wait... and I get this error in my RPT log; 

Error in expression < Error with Database Connection"]] call TON_fnc_logIt;};
_result = "extDB" callE>
13:34:36   Error position: <TON_fnc_logIt;};
_result = "extDB" callE>
13:34:36   Error Undefined variable in expression: ton_fnc_logit
13:34:36 File life_server\init.sqf, line 34
13:34:36 Error in expression <at["extDB: Version: %1",_result]]] call TON_fnc_logIt;
if(_result isEqualTo "") >
13:34:36   Error position: <TON_fnc_logIt;
if(_result isEqualTo "") >
13:34:36   Error Undefined variable in expression: ton_fnc_logit
13:34:36 File life_server\init.sqf, line 27

I haven't touched any of the code, unblocked all blocked files, have extDB v35 + it's requirements, but this seems to be the last piece of the puzzle I'm stuck at.

**Comment by Tomms123** [comment]
https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/life_server/script_macros.hpp

**Comment by DutchyD** [comment]
I know the variables are there, but I couldnt save my life to fix it. I'm new to this whole sqf code thingy.

**Comment by Tomms123** [comment]
Thats why you copy and paste the whole thing?

**Comment by DutchyD** [comment]
I've got the whole thing. I'm still getting the same error. Everything I have right now is the latest commit of this github page without any modifications.

**Comment by ShockiTV** [comment]
have u re-generated .pbo ?
