### ISSUE TITLE
code in core that doesnt make sense?

### ISSUE THREAD

**Issue by SamInside** [Itsyuka/Altis-Life#68]
Hi
its allready in 3.1.4.8

please have a look at the switch case:
https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/life_server/Functions/Systems/fn_cleanup.sqf#L27

it doesnt make sense at all or did i miss something?

**Comment by manzarek123** [comment]
Yep no sense.
The last case makes the others useless

**Comment by ColinM9991** [comment]
The more I look at Altis Life the more I realize that a lot of the code in it doesn't make sense or is just generally flawed.

For example, can anybody tell me why an array is created for _membersFinal in life_server\Functions\Gang\fn_updateGang.sqf which has a loop ran to push data in to it, but finally the _membersFinal variable is overwritten by getVariable "members".

Not to mention, the first array instance of _membersFinal within the loop is created within the local scope so it wouldn't even work anyway, and on top of that it's done inside the if statement which checks for higher members than the max group limit.
