### ISSUE TITLE
[SOLVED]SQL Database issue

### ISSUE THREAD

**Issue by ThatFellaNick** [Itsyuka/Altis-Life#75]
Hello im trying to run an Arma 3 Altis Life server and It involves MySQL databases. I've set up MySQL with xxamp and have gained access to phpmyadmin and the databases with my home connection. I've set up an account on mySQL with an IP of localhost and in the config for the game the IP is also localhost. But still I cant seem to connect in game just says creating character or something. Thank you so much for your time 

Config:
http://i.gyazo.com/50e31a6be20100dbaa4c9f38a43ea2e1.png

**Comment by ShockiTV** [comment]
If I remember correctly, current version is expecting database record with [AltisLife]
2nd, for clues check your rpt file and extDB/logs folder

**Comment by SgtMEverlast** [comment]
Pretty sure that issue is solved^
