### ISSUE TITLE
The fn_wantedGrab.sqf

### ISSUE THREAD

**Issue by LMLife** [Itsyuka/Altis-Life#78]
![](http://i.gyazo.com/f8f4ddab8c29dab00164563dd28ce92a.png)
This is a screen shoot of the error
------- The fn_wantedGrab.sqf -----
/*
	File: fn_wantedGrab.sqf
	Author: ColinM
	
	Description:
	Prepare the array to query the crimes.
*/
private["_display","_tab","_criminal"];
disableSerialization;
_display = findDisplay 2400;
_tab = _display displayCtrl 2402;
_criminal = lbData[2401,(lbCurSel 2401)];
_criminal = call compile format["%1", _criminal];

[[player,_criminal],"life_fnc_wantedCrimes",false,false] spawn life_fnc_MP;

**Comment by Provokan** [comment]
which Version u used? :)

**Comment by LMLife** [comment]
4.0

**Comment by LMLife** [comment]
aka this version 4.0 and 4.0 sql

**Comment by Provokan** [comment]
Okai, u use the first 4.0 version, download the new or follow the master Github

**Comment by Provokan** [comment]
https://github.com/Itsyuka/Altis-Life/commits/master

**Comment by BAROD** [comment]
because no criminals exist just replace this

https://github.com/BAROD/Altis-Life/commit/5787c964698c3541ed9b2ccba3c9539adfbda9e1
