### ISSUE TITLE
UPDATE fn_process action

### ISSUE THREAD

**Issue by Provokan** [Itsyuka/Altis-Life#82]
please chance this 

 case "oil": {["oilU","oilp",1200,(localize "STR_Process_Oil")];};

with

 case "oil": {["oil_unrefined","oil_refined",1200,(localize "STR_Process_Oil")];};

**Comment by Floxxe** [comment]
There is already a PullRequest.

**Comment by ShockiTV** [comment]
yes and Provokan's line was also off... :D
