### ISSUE TITLE
Arrested Issue

### ISSUE THREAD

**Issue by SgtMEverlast** [Itsyuka/Altis-Life#86]
Players that have been arrested will not spawn back in jail if they disconnected for lost connection in jail.
Players can not receive the arrested query correctly from DB. Apparently the player gets a request of false for arrested even if the db arrested is set 0 or 1. That's all I have been able to be-bug at this stage, if someone else could have a look at the issue that would be great.

**Comment by hitem** [comment]
Yeah, when a civ connects (initciv.sqf) it sends you to fn_jail.sqf, in that file you find the "if arrested exit with". try to exclude that one :+1:

**Comment by SgtMEverlast** [comment]
That's not the issue. The issue is when the server request query, it receives the correct value of 1, though when the value (7)selected & sent through the db-bool & sent to the player he gets false. I not sure why since other values are coming through correctly just the arrested.

I'll add a pastebin of the query's, getting closer to sorting this issue, just need to work out this last little bit. http://pastebin.com/aFYuCRan

**Comment by SgtMEverlast** [comment]
This can be closed issue solved ;p
