### ISSUE TITLE
Cant open house

### ISSUE THREAD

**Issue by zanris** [Itsyuka/Altis-Life#9]
we have problem with the houses, when you buy a house , you cant unlock the house, only lock, when you press U the text comes up LOCK , but not unlock :/ then i press again same text LOCK

**Comment by MaximumAltis** [comment]
I can lock and unlock my houses fine, are you using the very latest files from itsyuka github?

**Comment by zanris** [comment]
I have basiclly the standard files when i downloaded the server, can u Link the files u talk about, must be something wrong in house files or in keyhandler?

**Comment by ColinM9991** [comment]
Seeing no issues in the keyHandler file, I'd suggest downloading from Yuka's source again and seeing how it works out.

**Comment by zanris** [comment]
Could you Link where i can take a look and download thoose files? Thanks

**Comment by ColinM9991** [comment]
Just click "Altis Life" at the top after "Itsyuka"

**Comment by zanris** [comment]
Ok thanks!

i did see that i was missing this in keyhandler
gonna test and apply it, maybe will solve it ;)

if(_veh isKindOf "House_F" && {playerSide == civilian}) then {
if(_veh in life_vehicles && player distance _veh < 8) then {
_door = [_veh] call life_fnc_nearestDoor;
if(EQUAL(_door,0)) exitWith {hint localize "STR_House_Door_NotNear"};
_locked = _veh GVAR [format["bis_disabled_Door_%1",_door],0];
if(EQUAL(_locked,0)) then {
_veh SVAR [format["bis_disabled_Door_%1",_door],1,true];
_veh animate [format["door_%1_rot",_door],0];
systemChat localize "STR_House_Door_Lock";
} else {
_veh SVAR [format["bis_disabled_Door_%1",_door],0,true];
_veh animate [format["door_%1_rot",_door],1];
systemChat localize "STR_House_Door_Unlock";
};
};
} else {
