### ISSUE TITLE
House's say they are already owned when they are not

### ISSUE THREAD

**Issue by Scarso327** [Itsyuka/Altis-Life#90]
In the lastest update when I go to buy a house it keeps saying that they are all ready owned when no one owns a house on my server

**Comment by Tomms123** [comment]
Been reported several times

**Comment by Scarso327** [comment]
ye found that out about 2 hour after posting

**Comment by Provokan** [comment]
use this guy :) 

http://www.altisliferpg.com/topic/10245-fix-40-someone-already-owns-this-house-fix/

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/112

**Comment by midgetgrimm** [comment]
Problem fixed in main file. Committed. Fuck it YOLO
