### ISSUE TITLE
federal reserve

### ISSUE THREAD

**Issue by AlbertBellic** [Itsyuka/Altis-Life#91]
we cant take gold bar 
"You can't store anything but gold bars in the safe"

**Comment by ShockiTV** [comment]
in Altis_Life\dialog\function\fn_safeTake.sqf line 21
replace word "goldbar" with "goldBar", so it looks like this:
if(!(EQUAL(_ctrl,"goldBar"))) exitWith {hint localize "STR_Cop_OnlyGold"};

**Comment by AlbertBellic** [comment]
thx dude  =)
