### ISSUE TITLE
Bank Money reset to either 0 or 5000

### ISSUE THREAD

**Issue by jujubes55** [Itsyuka/Altis-Life#92]
Occasionally I get reports of players bank accounts being reset to $0 and when I look into the database their money has been reset to 5000. I'm wondering if anyone else is having this issue. I have looked into it pretty in depth and have not found any obvious causes. I'm thinking it may lie either in when the database is updated, or when the player information is pulled from the database. I have also looked at all logs and haven't seen anything.

**Comment by Tomms123** [comment]
Check so all vehicles in the master file is fully specified. If they're specified at the bottom but you can buy them and they take them out from the garage the money will get nulled as it dont know what the fee is.

**Comment by jujubes55** [comment]
Ok, Thanks Ill look into that. I did have a few missing entries that could be the issue.

**Comment by fresqo** [comment]
im having the same issue.. are you talking about the vehicles details in the buy sell arrays in the config.sqf?

**Comment by Scarso327** [comment]
go to the Config_vehicles.hpp and make sure every vehicle you have is specified in the cfg part.

**Comment by fresqo** [comment]
the bank reset happens every time someone gets revived. still think its the vehicle thing??

**Comment by Tomms123** [comment]
fresqo look in your darn RPT, if it doesnt say anything then check your files
