### ISSUE TITLE
Wanted List always displaying "No Criminals"

### ISSUE THREAD

**Issue by jujubes55** [Itsyuka/Altis-Life#93]
The wanted list continuously displays "No Criminals" even though there are several criminals active on the server. Not sure if the issue is within the database connection or a UI issue. No logs have given any insight. Any help would be greatly appreciated.

**Comment by BAROD** [comment]
Ui

**Comment by Scarso327** [comment]
I am getting this two. I have been looking for the problem but can't find it.

**Comment by hitem** [comment]
https://github.com/BAROD/Altis-Life/commit/5787c964698c3541ed9b2ccba3c9539adfbda9e1
I think thats a solution posted by Bardoc under: https://github.com/Itsyuka/Altis-Life/issues/78
I guess you tried that already maybe? else it might help!

**Comment by jujubes55** [comment]
Yeah. I added that change but it just displays no criminals at the bottom. List is still empty.

**Comment by Scarso327** [comment]
Hope someone finds the problem soon... I am look at it but still can't find it

**Comment by Floxxe** [comment]
This fix by BAROD works: https://github.com/BAROD/Altis-Life/commit/5787c964698c3541ed9b2ccba3c9539adfbda9e1

**Comment by Scarso327** [comment]
wow that was easy... I feel stuiped now

**Comment by jujubes55** [comment]
I applied that fix a while ago but it didn't fix anything except changing the location of where "No Criminals" is located. Wanted list still displays nothing for me.

**Comment by Scarso327** [comment]
ye It worked and then after a while it did not.. I think it is when the civ is already wanted then a cop comes on and they appear I have not tested this fix other then seeing it not work alot of the time

**Comment by AlbertBellic** [comment]
is no work for me , before fix i only can add people but i show then and after fix nothing in the list

**Comment by Provokan** [comment]
link are broken ;D

**Comment by Provokan** [comment]
link its down :)

**Comment by SaurusMaster** [comment]
if(((lbSize _list)-1) == -1) then
{
	_list lbAdd "No criminals";
}; 

to

if(((lbSize _list)-1) == -1) then
{
	ctrlSetText[2403,"No criminals"]; 
};

**Comment by AlbertBellic** [comment]
http://www.altisliferpg.com/topic/10431-extdb-wanted-list-issue/?hl=wanted

**Comment by Provokan** [comment]
i become only this error :-> see picture
http://www.directupload.net/file/d/3975/bcgqqop7_jpg.htm
