### ISSUE TITLE
Gang Hideout bug after last update

### ISSUE THREAD

**Issue by mjmfighter** [Itsyuka/Altis-Life#96]
A gang hideout bug has appeared after the last arma update.  The issue has to do with the command nearestBuilding.  It does not return the spawned in barracks anymore and needs to be replaced in the mission.sqm file.

This:
_b = nearestBuilding (getPosATL player);

Needs to be replaced by this:

_b = (nearestObjects[getPosATL player,[""Land_u_Barracks_V2_F"",""Land_i_Barracks_V2_F""],25]) select 0

Or similar code using nearestObject or nearestObjects.  nearestBuilding will not work anymore.

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/Altis_Life.Altis/core/actions/fn_captureHideout.sqf#L9

close

**Comment by mjmfighter** [comment]
ehm

https://github.com/Itsyuka/Altis-Life/blob/master/extDB-Build/Altis_Life.Altis/mission.sqm#L7755

still effected.  Please read my report, says mission.sqm file, not fn_captureHideout.sqf file.

**Comment by BAROD** [comment]
upps

**Comment by BAROD** [comment]
https://github.com/Itsyuka/Altis-Life/pull/114
