### ISSUE TITLE
Housing Issue

### ISSUE THREAD

**Issue by SgtMEverlast** [Itsyuka/Altis-Life#99]
After players joining back on the server after a restart these a chance that they will find default Nato gear in the housing crates, I do remember finding a post related to the issue, though I have not found this post again since I am now come across the issue on 4.0.

If anyone who knows the fix for this, that would be great.

**Comment by AlbertBellic** [comment]
they have some weapon in the box ????

**Comment by SgtMEverlast** [comment]
Yes

**Comment by breaup** [comment]
|Tough it was one of my admin trolling me but I guess I am having the same issue. :P

**Comment by AlbertBellic** [comment]
then i got the same issue

**Comment by Nasdero** [comment]
You mean this maybe, but it is not for 4.0: http://www.altisliferpg.com/topic/10245-fix-40-someone-already-owns-this-house-fix/?p=64110
I got the same yesterday, I will try to fix it.

**Comment by AveUrsus** [comment]
guys, is any solution for this trouble?
Getting NATO box in 4 slot houses and 3 slot houses.
